version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    steps:
      - checkout
      - run: npm install
      - run: npm run test:unit
      - run: npm run test:e2e
      - run: npm run build
  deploy:
    steps:
      - checkout
workflows:
    start:
      jobs:
        - build-and-test
